// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpFEqU0gbMHBukG7FxpD9fzcIL3VKR-EY',
    appId: '1:991444383281:web:6df8f7af8d16eb553c8710',
    messagingSenderId: '991444383281',
    projectId: 'chat-app-d762a',
    authDomain: 'chat-app-d762a.firebaseapp.com',
    storageBucket: 'chat-app-d762a.appspot.com',
    measurementId: 'G-SXD8TP5YPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_RIzSfAAX-F12lz_kSLdk_6XP8nLXBnE',
    appId: '1:991444383281:android:55c016d41494deeb3c8710',
    messagingSenderId: '991444383281',
    projectId: 'chat-app-d762a',
    storageBucket: 'chat-app-d762a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs1rxLZF9oe58FJEU9b-GhIw2NIO80STI',
    appId: '1:991444383281:ios:9dfe370fb5446d563c8710',
    messagingSenderId: '991444383281',
    projectId: 'chat-app-d762a',
    storageBucket: 'chat-app-d762a.appspot.com',
    iosBundleId: 'com.example.chatAppSecond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs1rxLZF9oe58FJEU9b-GhIw2NIO80STI',
    appId: '1:991444383281:ios:9acec36c90ae16ed3c8710',
    messagingSenderId: '991444383281',
    projectId: 'chat-app-d762a',
    storageBucket: 'chat-app-d762a.appspot.com',
    iosBundleId: 'com.example.chatAppSecond.RunnerTests',
  );
}
